# Generated by Django 4.2.2 on 2023-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                        unique=True
                    ),
                ),
                ("name", models.CharField(default="", max_length=70)),
                ("email", models.CharField(default="", max_length=45)),
                ("password", models.CharField(default="", max_length=45)),
            ],
        ),
    ]
