# Generated by Django 4.2.2 on 2023-07-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="foto_url",
            field=models.URLField(max_length=300),
        ),
    ]
