# Generated by Django 4.2.2 on 2023-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposrecursos',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
