# Generated by Django 4.2.2 on 2023-07-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_local_foto_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dispositivoauxiliarmarcha",
            old_name="dispositivo_id",
            new_name="dispositivo",
        ),
        migrations.RenameField(
            model_name="dispositivoauxiliarmarcha",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="locaisinteresse",
            old_name="recurso_id",
            new_name="tipo_local_id",
        ),
        migrations.RenameField(
            model_name="recursosacessibilidade",
            old_name="tipo_local_id",
            new_name="recurso",
        ),
        migrations.RenameField(
            model_name="recursosacessibilidade",
            old_name="user_id",
            new_name="user",
        ),
    ]
