# Generated by Django 4.2.2 on 2023-07-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0003_rename_dispositivo_id_dispositivoauxiliarmarcha_dispositivo_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DispositivoAuxiliarMarcha",
            new_name="PreferenciaDispositivos",
        ),
        migrations.RenameModel(
            old_name="LocaisInteresse",
            new_name="PreferenciaLocais",
        ),
        migrations.RenameModel(
            old_name="RecursosAcessibilidade",
            new_name="PreferenciaRecursos",
        ),
        migrations.RenameModel(
            old_name="ListaDispositivos",
            new_name="TiposDispositivos",
        ),
        migrations.RenameModel(
            old_name="ListaRecursos",
            new_name="TiposRecursos",
        ),
        migrations.RenameField(
            model_name="preferencialocais",
            old_name="tipo_local_id",
            new_name="local",
        ),
        migrations.RenameField(
            model_name="preferencialocais",
            old_name="user_id",
            new_name="user",
        ),
    ]
