# Generated by Django 3.2.9 on 2023-08-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_dispositivoauxiliarmarcha_preferenciadispositivos_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='userprofile',
            name='cluster_usuario',
            field=models.IntegerField(null=True),
        ),
    ]
