# Generated by Django 4.2.2 on 2023-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_myuser_is_admin_remove_myuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
