# Generated by Django 4.2.4 on 2023-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_auto_20230811_0820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cluster_usuario",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="duracao_condicao",
            field=models.CharField(
                choices=[
                    ("progressiva/degenerativa", "Progressiva/Degenerativa"),
                    ("temporaria", "Temporária"),
                    ("estavel ou permanente", "Estável ou Permanente"),
                ],
                default="temporaria",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("acompanhante", "Acompanhante"),
                    ("pmlr", "Pessoa com mobilidade de locomoção reduzida"),
                    ("outro", "Outro"),
                ],
                default="temporaria",
                max_length=50,
            ),
        ),
    ]
