# Generated by Django 4.2.2 on 2023-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_myuser_is_active_myuser_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="is_active",
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
