# Generated by Django 4.2.2 on 2023-07-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_myuser_is_active_myuser_is_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("recursos", models.TextField()),
                ("cep", models.CharField(max_length=10)),
                ("foto_url", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
