# Generated by Django 4.2.4 on 2023-08-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_preferenciadispositivos_cluster_usuario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferenciadispositivos",
            name="cluster_usuario",
        ),
    ]
