# Generated by Django 4.2.2 on 2023-07-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_local"),
    ]

    operations = [
        migrations.AddField(
            model_name="local",
            name="tipo",
            field=models.CharField(default="", max_length=100),
        ),
    ]
