# Generated by Django 4.2.2 on 2023-07-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_local_nota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="local",
            name="nota",
        ),
    ]
