# Generated by Django 4.2.2 on 2023-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_local_nota_local_relevancia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="foto_url",
            field=models.CharField(max_length=255),
        ),
    ]
