# Generated by Django 4.2.2 on 2023-08-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('local1', models.IntegerField()),
                ('local2', models.IntegerField()),
                ('local3', models.IntegerField()),
                ('local4', models.IntegerField()),
            ],
        ),
    ]
