USE mydb;

INSERT INTO myapp_listarecursos (title) VALUES
('elevador'),
('plataforma elevatória'),
('ponto de taxi'),
('sinalização'),
('rampas'),
('corrimões'),
('portas amplas'),
('calçada acessível'),
('vagas preferenciais'),
('banheiro família'),
('barras de apoio'),
('ponto de ônibus'),
('funcionários treinados'),
('filas preferenciais'),
('banheiro adaptado'),
('piso nivelado'),
('área de transferência'),
('barra sanitária'),
('piso antiderrapante'),
('guia rebaixada'),
('piso não trepidante');

INSERT INTO myapp_listadispositivos (title) VALUES
('bengala'),
('muleta'),
('andador'),
('cadeira de rodas motorizada'),
('cadeiras de rodas manual'),
('cadeira de rodas monobloco'),
('cadeira de rodas dobravel em x'),
('cadeira de rodas com elevação automatica'),
('protese'),
('ortese');

INSERT INTO myapp_tiposlocais (title) VALUES
('igreja'),
('museu'),
('estátua'),
('parque'),
('praia'),
('teatro'),
('biblioteca'),
('monumento'),
('galeria'),
('mercado'),
('jardim botânico'),
('zoológico'),
('catedral'),
('sinagoga'),
('mesquita'),
('castelo'),
('palácio'),
('torre'),
('observatório'),
('planetário'),
('aquário'),
('farol'),
('ilha'),
('praça');