# Generated by Django 4.2.2 on 2023-09-02 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local_interactions', '0001_initial'),
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.local', verbose_name='local'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='post',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.local', verbose_name='local'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_interactions.rating', verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='localtags',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.local'),
        ),
        migrations.AddField(
            model_name='localtags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tiposrecursos'),
        ),
    ]
